# encoding: UTF-8
require 'mechanize'
require 'set'
require 'json'

def title_to_country_code(title)
	case title
	when '美國USA'
		return 'US'
	when '西班牙 Spain'
		return 'ES'
	when '澳大利亞Australia'
		 return 'AU'
	when '孟加拉Bangladesh '
		 return 'BD'
	when '不丹Bhutan'
		 return 'BT'
	when '汶萊Brunei Darussalam'
		 return 'BN'
	when '柬埔寨Cambodia'
		 return 'KH'
	when '印度India'
		 return 'IN'
	when '印尼Indonesia'
		 return 'ID'
	when '北韓Korea(North Korea)'
		 return 'KP'
	when '韓國Korea(South Korea)'
		 return 'KR'
	when '寮國Lao People\'s Dem Rep'
		 return 'LA'
	when '馬來西亞Malaysia'
		 return 'MY'
	when '馬爾地夫Maldives'
		 return 'MV'
	when '緬甸Myanmar'
		 return 'MM'
	when '尼泊爾Nepal'
		 return 'NP'
	when '巴布亞紐幾內亞Papua New Guinea'
		 return 'PG'
	when '菲律賓Philippines'
		 return 'PH'
	when '斐濟Republic of Fiji '
		 return 'FJ'
	when '索羅門群島Solomon Islands '
		 return 'SB'
	when '斯里蘭卡Sri Lanka '
		 return 'LK'
	when '泰國Thailand'
		 return 'TH'
	when '東帝汶Timor Leste'
		 return 'TL'
	when '吐瓦魯Tuvalu'
		 return 'TV'
	when '阿富汗Afghanistan'
		 return 'AF'
	when '巴林王國Bahrain'
		 return 'BH'
	when '白俄羅斯Belarus '
		 return 'BY'
	when '喬治亞Georgia'
		 return 'GE'
	when '伊朗Iran'
		 return 'IR'
	when '伊拉克Iraq'
		 return 'IQ'
	when '以色列Israel'
		 return 'IL'
	when '約旦Jordan'
		 return 'JO'
	when '吉爾吉斯Kyrgyzstan'
		 return 'KG'
	when '黎巴嫩Lebanon'
		 return 'LB'
	when '巴基斯坦Pakistan'
		 return 'PK'
	when '俄羅斯Russian Federation '
		 return 'RU'
	when '沙烏地阿拉伯Saudi Arabia'
		 return 'SA'
	when '敘利亞Syrian Arab Rep'
		 return 'SY'
	when '塔吉克Tajikistan'
		 return 'TJ'
	when '土耳其Turkey'
		 return 'TR'
	when '烏克蘭Ukraine'
		 return 'UA'
	when '烏茲別克Uzbekistan'
		 return 'UZ'
	when '葉門Yemen '
		 return 'YE'
	when '阿爾及利亞Algeria'
		 return 'DZ'
	when '安哥拉Angola'
		 return 'AO'
	when '貝南共和國Benin,Republic of '
		 return 'BJ'
	when '波札那共和國Botswana '
		 return 'BW'
	when '布吉納法索Burkina Faso'
		 return 'BF'
	when '蒲隆地Burundi'
		 return 'BI'
	when '中非共和國Central African Republic'
		 return 'CF'
	when '查德Chad'
		 return 'TD'
	when '葛摩聯盟Comoros,Union of'
		 return 'KM'
	when '剛果民主共和國Congo,Democratic Republic of the'
		 return 'CD'
	when '剛果共和國Congo,Republic of the '
		 return 'CG'
	when '象牙海岸Cote d\'Ivoire'
		 return 'CI'
	when '吉布地共和國Djibouti,Republic of '
		 return 'DJ'
	when '埃及Egypt'
		 return 'EG'
	when '厄利垂亞Eritrea'
		 return 'ER'
	when '衣索比亞Ethiopia'
		 return 'ET'
	when '加彭Gabon'
		 return 'GA'
	when '迦納共和國Ghana'
		 return 'GH'
	when '幾內亞Guinea'
		 return 'GN'
	when '幾內亞比索Guinea Bissau'
		 return 'GW'
	when '肯亞Kenya'
		 return 'KE'
	when '賴索托Lesotho'
		 return 'LS'
	when '賴比瑞亞Liberia'
		 return 'LR'
	when '利比亞Libya '
		 return 'LY'
	when '馬達加斯加 Madagascar'
		 return 'MG'
	when '馬拉威Malawi'
		 return 'MW'
	when '馬利Mali,Republic of '
		 return 'ML'
	when '茅利塔尼亞 Mauritania'
		 return 'MR'
	when '模里西斯Mauritius'
		 return 'MU'
	when '摩洛哥Morocco'
		 return 'MA'
	when '莫三比克 Mozambique'
		 return 'MZ'
	when '納米比亞Namibia '
		 return 'NA'
	when '尼日Niger'
		 return 'NE'
	when '奈及利亞Nigeria'
		 return 'NG'
	when '喀麥隆Republic of Cameroon '
		 return 'CM'
	when '聖多美普林西比Sao Tome and Principe '
		 return 'ST'
	when '塞內加爾Senegal'
		 return 'SN'
	when '塞席爾Seychelles'
		 return 'SC'
	when '獅子山Sierra Leone'
		 return 'SL'
	when '索馬利亞Somalia'
		 return 'SO'
	when '南非South Africa'
		 return 'ZA'
	when '南蘇丹共和國South Sudan,Republic of '
		 return 'SS'
	when '蘇丹Sudan'
		 return 'SD'
	when '坦尚尼亞Tanzania'
		 return 'TZ'
	when '多哥Togo'
		 return 'TG'
	when '突尼西亞Tunisia'
		 return 'TN'
	when '烏干達 Uganda'
		 return 'UG'
	when '尚比亞 Zambia'
		 return 'ZM'
	when '辛巴威Zimbabwe'
		 return 'ZW'
	when '阿爾巴尼亞Albania'
		 return 'AL'
	when '安道爾Andorra'
		 return 'AD'
	when '奧地利 Austria '
		 return 'AT'
	when '比利時Belgium'
		 return 'BE'
	when '波士尼亞與赫塞哥維納Bosnia and Herzegovina'
		 return 'BA'
	when '保加利亞Bulgaria'
		 return 'BG'
	when '克羅埃西亞Croatia'
		 return 'HR'
	when '賽普勒斯Cyprus'
		 return 'CY'
	when '捷克Czech'
		 return 'CZ'
	when '丹麥Denmark'
		 return 'DK'
	when '愛沙尼亞Estonia '
		 return 'EE'
	when '芬蘭Finland'
		 return 'FI'
	when '法國France '
		 return 'FR'
	when '德國Germany'
		 return 'DE'
	when '希臘Greece '
		 return 'GR'
	when '教廷Holy See'
		 return 'VA'
	when '匈牙利Hungary '
		 return 'HU'
	when '冰島Iceland'
		 return 'IS'
	when '義大利Italy'
		 return 'IT'
	when '科索沃共和國Kosovo'
		 return 'XK'
	when '拉脫維亞Latvia'
		 return 'LV'
	when '列支敦斯登Liechtenstein'
		 return 'LI'
	when '立陶宛Lithuania'
		 return 'LT'
	when '盧森堡Luxembourg '
		 return 'LU'
	when '馬其頓Macedonia '
		 return 'MK'
	when '馬爾他Malta'
		 return 'MT'
	when '摩納哥Monaco'
		 return 'MC'
	when '蒙特內哥羅Montenegro'
		 return 'ME'
	when '荷蘭Netherlands '
		 return 'NL'
	when '挪威Norway'
		 return 'NO'
	when '波蘭Poland'
		 return 'PL'
	when '葡萄牙Portugal'
		 return 'PT'
	when '愛爾蘭共和國Republic of Ireland'
		 return 'IE'
	when '羅馬尼亞Romania'
		 return 'RO'
	when '聖馬利諾San Marino'
		 return 'SM'
	when '塞爾維亞共和國Serbia'
		 return 'RS'
	when '斯洛伐克Slovakia '
		 return 'SK'
	when '斯洛維尼亞Slovenia'
		 return 'SI'
	when '瑞典Sweden'
		 return 'SE'
	when '瑞士Switzerland '
		 return 'CH'
	when '英國United Kingdom of Great Britain and Northern Ireland'
		 return 'GB'
	when '阿根廷Argentina '
		 return 'AR'
	when '玻利維亞Bolivia'
		 return 'BO'
	when '巴西Brazil'
		 return 'BR'
	when '智利Chile'
		 return 'CL'
	when '哥倫比亞Colombia'
		 return 'CO'
	when '古巴Cuba'
		 return 'CU'
	when '多明尼加Dominican Rep.'
		 return 'DO'
	when '厄瓜多Ecuador'
		 return 'EC'
	when '薩爾瓦多El Salvador '
		 return 'SV'
	when '法屬圭亞那French Guiana'
		 return 'GF'
	when '格瑞那達Grenada'
		 return 'GD'
	when '瓜地馬拉Guatemala'
		 return 'GT'
	when '蓋亞那共和國Guyana '
		 return 'GY'
	when '海地Haiti'
		 return 'HT'
	when '宏都拉斯Honduras'
		 return 'HN'
	when '牙買加Jamaica'
		 return 'JM'
	when '巴拿馬共和國Panama'
		 return 'PA'
	when '巴拉圭Paraguay'
		 return 'PY'
	when '秘魯Peru'
		 return 'PE'
	when '聖克里斯多福及尼維斯Saint Christopher (St. Kitts) and Nevis'
		 return 'KN'
	when '蘇利南Suriname'
		 return 'SR'
	when '千里達及托巴哥Trinidad and Tobago'
		 return 'TT'
	when '委內瑞拉Venezuela'
		 return 'VE'
	else
		# puts "when '#{title}'"
		# puts "\t return ''"
		puts "unknown country #{title}"
		return 'UNDEFINED'
	end
end
def icon_url_to_level(url)
	case url
	when '/xslgip/spring2012/images/gray_icon.gif'
		return 1
	when '/xslgip/spring2012/images/yellow_icon.gif'
		return 2
	when '/xslgip/spring2012/images/orange_icon.gif'
		return 3
	when '/xslgip/spring2012/images/red_icon.gif'
		return 4
	end
	return 0
end
mechanize = Mechanize.new { |agent|
	agent.user_agent_alias = 'Mac Safari'
}
visited_list = Set.new
urls = Set.new
np = mechanize.get("http://www.boca.gov.tw/lp.asp?ctNode=754&CtUnit=32&BaseDSD=13&mp=1")
alert_data = {'MAX' => 4, 'MIN' => 0}
np.search(".content_box>.body>ul>li").each{|e|
	alert_data[title_to_country_code(e.search('a')[0]["title"])] = icon_url_to_level(e.search('img')[0]["src"])
}
File.open("js/country_alert_data.js","w") do |f|
  f.write('alert_data = '+alert_data.to_json)
end